export class Employee{
    id : number ;
    username :  string  ;
    password :  string  ;
    UserCode : number ;
    first_name :  string  ;
    last_name :  string  ;
    UserBirthDate :  Object  ;
    EntryDate :  Object  ;
    joinedDate :  Object  ;
    UserMobile : string ;
    email : string   ;
    is_superuser : boolean ;
    is_staff : boolean ;
    is_active : boolean ;
    is_employee :  string  ;
    is_teacher :  string  ;
    periorty : number ;
    COMId : number ;
    branch_KeyField : number ;
    userPicture : File;
    gender :  string  ;
    RowDelete : number ;
    LoginFrom :  string  ;
    userJobName :  string  ;
    userFacebook :  string  ;
    userTwitter :  string  ;
    userGoogle :  string  ;
    userAddress :  string  ;
}
